In [1]:
#!pip install pandas

# Gather all data

In [2]:
import csv
import json
import pandas as pd
from datetime import datetime
import numpy as np
from collections import Counter
from os.path import exists
import os


import warnings
warnings.filterwarnings("ignore")


outputFolders = "../data_2019_processed/"

In [3]:
# Dataframe of all datasets
# initialize list of lists
datasets = ['0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs',
            '0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA', 
            '2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0', 
            '2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys', 
            #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
            '7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA', 
            'a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4', 
            'ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc', 
            'Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U', 
            'CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA', 
            'DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc', 
            'DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA', 
            'dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY', 
            'HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo', 
            'jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw', 
            'JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I', 
            'K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8', 
            'oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q', 
            'pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM', 
            'PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc', 
            'QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ', 
            'rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw', 
            'RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI', 
            'SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4', 
            'VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is', 
            'Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw', 
            'XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA', 
            'YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw', 
            'ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM', 
            'ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']
  
# Create the pandas DataFrame
folders = pd.DataFrame(datasets, columns=['folder'])

#folders

In [4]:
pd.read_csv("../../Dataset_ECUADOR_2019/0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs/sleep_form_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs.csv")

,Unnamed: 0,sleep_time,wakeup_time,sleep,arousal,valence,dominance,physical_activity,sociability,study,timestamp
0,0,2018-05-15T05:30:29Z,2018-05-15T11:30:29Z,3,3,3,4,3,4,3,2018-05-15T14:31:29Z
1,1,2018-05-15T17:00:00Z,2018-05-16T11:00:04Z,3,4,3,4,3,4,2,2018-05-16T14:07:04Z
2,2,2018-05-15T17:00:00Z,2018-05-16T11:00:08Z,3,4,3,4,3,4,2,2018-05-16T14:07:08Z
3,3,2018-05-17T04:45:00Z,2018-05-17T11:15:19Z,3,0,4,3,1,2,1,2018-05-17T14:16:19Z
4,4,2018-05-18T03:00:00Z,2018-05-18T08:30:49Z,1,0,1,1,0,0,1,2018-05-18T15:12:49Z
5,5,2018-05-19T05:00:53Z,2018-05-19T10:15:53Z,3,3,1,3,2,2,4,2018-05-19T15:51:53Z
6,6,2018-05-21T06:15:52Z,2018-05-21T10:30:52Z,4,0,2,0,1,2,3,2018-05-21T15:33:52Z
7,7,2018-05-22T04:45:00Z,2018-05-22T11:30:21Z,3,1,3,3,3,2,3,2018-05-22T13:55:21Z
8,8,2018-05-22T04:30:00Z,2018-05-22T11:30:40Z,3,1,3,2,3,2,3,2018-05-22T15:59:40Z
9,9,2018-05-23T15:00:09Z,2018-05-23T12:30:09Z,2,2,3,3,1,2,2,2018-05-23T15:44:09Z
10,10,2018-05-24T04:30:00Z,2018-05-24T10:30:33Z,1,2,1,2,1,1,2,2018-05-24T14:15:33Z
11,11,2018-05-25T04:30:00Z,2018-05-25T12:30:37Z,3,0,2,3,1,1,4,2018-05-25T15:56:37Z
12,12,2018-05-26T06:30:12Z,2018-05-26T12:30:12Z,3,1,3,2,2,1,4,2018-05-26T14:40:12Z
13,13,2018-05-26T06:45:29Z,2018-05-26T12:30:29Z,3,1,4,2,1,1,4,2018-05-26T15:48:29Z
14,14,2018-05-27T18:00:56Z,2018-05-27T14:00:56Z,0,0,0,0,0,0,0,2018-05-27T18:03:56Z
15,15,2018-05-27T10:00:16Z,2018-05-27T18:00:16Z,0,0,0,0,0,0,0,2018-05-27T18:56:16Z
16,16,2018-05-28T06:30:08Z,2018-05-28T10:30:08Z,2,2,3,2,3,3,4,2018-05-28T17:34:08Z
17,17,2018-05-30T06:45:35Z,2018-05-30T12:00:35Z,2,1,2,3,1,1,3,2018-05-30T15:56:35Z
18,18,2018-05-31T07:00:27Z,2018-05-31T10:30:27Z,3,0,3,0,1,1,3,2018-05-31T13:08:27Z
19,19,2018-06-01T07:00:56Z,2018-06-01T10:30:56Z,0,1,1,1,1,0,4,2018-06-01T16:40:56Z
20,20,2018-06-01T16:45:00Z,2018-06-02T13:30:12Z,4,2,4,3,1,3,4,2018-06-03T03:45:12Z
21,21,2018-06-03T07:00:00Z,2018-06-03T15:00:00Z,0,0,0,0,0,0,0,2018-06-03T15:06:00Z
22,22,2018-06-03T04:45:00Z,2018-06-03T13:30:37Z,3,2,0,1,1,0,4,2018-06-03T16:37:37Z
23,23,2018-06-04T05:45:42Z,2018-06-04T11:00:42Z,4,1,3,1,3,3,4,2018-06-04T15:44:42Z
24,24,2018-06-05T14:00:12Z,2018-06-05T14:00:12Z,0,0,0,0,0,0,0,2018-06-05T14:09:12Z
25,25,2018-06-05T04:45:00Z,2018-06-05T11:30:58Z,3,2,1,2,2,1,3,2018-06-05T16:02:58Z
26,26,2018-06-06T06:00:16Z,2018-06-06T12:00:16Z,3,3,3,3,4,3,4,2018-06-06T15:46:16Z
27,27,2018-06-07T04:30:00Z,2018-06-07T10:30:58Z,3,1,3,1,3,2,4,2018-06-07T16:21:58Z
28,28,2018-06-08T05:00:35Z,2018-06-08T13:00:35Z,0,0,0,0,0,0,0,2018-06-08T13:12:35Z
29,29,2018-06-08T04:45:00Z,2018-06-08T10:00:34Z,3,1,3,3,1,3,4,2018-06-08T15:52:34Z
30,30,2018-06-10T06:30:11Z,2018-06-10T12:30:11Z,4,1,3,2,3,3,4,2018-06-10T15:37:11Z
31,31,2018-06-11T05:30:45Z,2018-06-11T10:30:45Z,3,1,3,3,3,3,4,2018-06-11T13:54:45Z
32,32,2018-06-12T08:00:34Z,2018-06-12T16:00:34Z,0,0,0,0,0,0,0,2018-06-12T16:14:34Z

In [5]:
pd.read_csv("../data_2019_processed/form/sleep_form_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs_treated.csv")

,Unnamed: 0.1,index,Unnamed: 0,sleep_time,wakeup_time,sleep,arousal,valence,dominance,physical_activity,sociability,study,timestamp,time_sleeping,time_sleeping_hs,duplicated
0,0,0,0,1.526359e+09,1.526380e+09,3,3,3,4,3,4,3,2018-05-15T14:31:29Z,21600.0,6.000000,0
1,2,2,2,1.526400e+09,1.526465e+09,3,4,3,4,3,4,2,2018-05-16T14:07:08Z,64808.0,18.002222,0
2,3,3,3,1.526529e+09,1.526552e+09,3,0,4,3,1,2,1,2018-05-17T14:16:19Z,23419.0,6.505278,0
3,4,4,4,1.526609e+09,1.526629e+09,1,0,1,1,0,0,1,2018-05-18T15:12:49Z,19849.0,5.513611,0
4,5,5,5,1.526702e+09,1.526721e+09,3,3,1,3,2,2,4,2018-05-19T15:51:53Z,18900.0,5.250000,0
5,6,6,6,1.526880e+09,1.526895e+09,4,0,2,0,1,2,3,2018-05-21T15:33:52Z,15300.0,4.250000,0
6,8,8,8,1.526960e+09,1.526985e+09,3,1,3,2,3,2,3,2018-05-22T15:59:40Z,25240.0,7.011111,0
7,9,9,9,1.527075e+09,1.527084e+09,2,2,3,3,1,2,2,2018-05-23T15:44:09Z,9000.0,2.500000,0
8,10,10,10,1.527133e+09,1.527154e+09,1,2,1,2,1,1,2,2018-05-24T14:15:33Z,21633.0,6.009167,0
9,11,11,11,1.527219e+09,1.527248e+09,3,0,2,3,1,1,4,2018-05-25T15:56:37Z,28837.0,8.010278,0
10,13,13,13,1.527314e+09,1.527334e+09,3,1,4,2,1,1,4,2018-05-26T15:48:29Z,20700.0,5.750000,0
11,15,15,15,1.527412e+09,1.527440e+09,0,0,0,0,0,0,0,2018-05-27T18:56:16Z,28800.0,8.000000,0
12,16,16,16,1.527485e+09,1.527500e+09,2,2,3,2,3,3,4,2018-05-28T17:34:08Z,14400.0,4.000000,0
13,17,17,17,1.527659e+09,1.527678e+09,2,1,2,3,1,1,3,2018-05-30T15:56:35Z,18900.0,5.250000,0
14,18,18,18,1.527746e+09,1.527759e+09,3,0,3,0,1,1,3,2018-05-31T13:08:27Z,12600.0,3.500000,0
15,19,19,19,1.527833e+09,1.527845e+09,0,1,1,1,1,0,4,2018-06-01T16:40:56Z,12600.0,3.500000,0
16,20,20,20,1.527868e+09,1.527943e+09,4,2,4,3,1,3,4,2018-06-03T03:45:12Z,74712.0,20.753333,0
17,22,22,22,1.527998e+09,1.528029e+09,3,2,0,1,1,0,4,2018-06-03T16:37:37Z,31537.0,8.760278,0
18,23,23,23,1.528088e+09,1.528106e+09,4,1,3,1,3,3,4,2018-06-04T15:44:42Z,18900.0,5.250000,0
19,24,25,25,1.528170e+09,1.528195e+09,3,2,1,2,2,1,3,2018-06-05T16:02:58Z,24358.0,6.766111,0
20,25,26,26,1.528261e+09,1.528283e+09,3,3,3,3,4,3,4,2018-06-06T15:46:16Z,21600.0,6.000000,0
21,26,27,27,1.528342e+09,1.528364e+09,3,1,3,1,3,2,4,2018-06-07T16:21:58Z,21658.0,6.016111,0
22,28,29,29,1.528430e+09,1.528448e+09,3,1,3,3,1,3,4,2018-06-08T15:52:34Z,18934.0,5.259444,0
23,29,30,30,1.528609e+09,1.528630e+09,4,1,3,2,3,3,4,2018-06-10T15:37:11Z,21600.0,6.000000,0
24,30,31,31,1.528691e+09,1.528709e+09,3,1,3,3,3,3,4,2018-06-11T13:54:45Z,18000.0,5.000000,0
25,31,32,32,1.528787e+09,1.528816e+09,0,0,0,0,0,0,0,2018-06-12T16:14:34Z,28800.0,8.000000,0

In [6]:
X = pd.read_csv("../data_2019_processed/form/sleep_form_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs_treated.csv")

pd.to_datetime(X['timestamp'])

0    2018-05-15 14:31:29+00:00
1    2018-05-16 14:07:08+00:00
2    2018-05-17 14:16:19+00:00
3    2018-05-18 15:12:49+00:00
4    2018-05-19 15:51:53+00:00
5    2018-05-21 15:33:52+00:00
6    2018-05-22 15:59:40+00:00
7    2018-05-23 15:44:09+00:00
8    2018-05-24 14:15:33+00:00
9    2018-05-25 15:56:37+00:00
10   2018-05-26 15:48:29+00:00
11   2018-05-27 18:56:16+00:00
12   2018-05-28 17:34:08+00:00
13   2018-05-30 15:56:35+00:00
14   2018-05-31 13:08:27+00:00
15   2018-06-01 16:40:56+00:00
16   2018-06-03 03:45:12+00:00
17   2018-06-03 16:37:37+00:00
18   2018-06-04 15:44:42+00:00
19   2018-06-05 16:02:58+00:00
20   2018-06-06 15:46:16+00:00
21   2018-06-07 16:21:58+00:00
22   2018-06-08 15:52:34+00:00
23   2018-06-10 15:37:11+00:00
24   2018-06-11 13:54:45+00:00
25   2018-06-12 16:14:34+00:00
Name: timestamp, dtype: datetime64[ns, UTC]

In [7]:
X['sleep_time'],

(0     1.526359e+09
 1     1.526400e+09
 2     1.526529e+09
 3     1.526609e+09
 4     1.526702e+09
 5     1.526880e+09
 6     1.526960e+09
 7     1.527075e+09
 8     1.527133e+09
 9     1.527219e+09
 10    1.527314e+09
 11    1.527412e+09
 12    1.527485e+09
 13    1.527659e+09
 14    1.527746e+09
 15    1.527833e+09
 16    1.527868e+09
 17    1.527998e+09
 18    1.528088e+09
 19    1.528170e+09
 20    1.528261e+09
 21    1.528342e+09
 22    1.528430e+09
 23    1.528609e+09
 24    1.528691e+09
 25    1.528787e+09
 Name: sleep_time, dtype: float64,)

In [9]:

#test.astype(int).div(10**9)

In [10]:
#test

# Data pre-processing

In [11]:
print("Loading data")

allData = pd.DataFrame()

clientData = []

for indexFolder, folder in folders.iterrows():

    # check f the path exists (becouse kaggle removed the + character from file names)
    fileName = folder['folder']
    if(not(exists("../../Dataset_ECUADOR_2019/"+folder['folder']+"/"+fileName+".csv"))):
        fileName = folder['folder'].replace("+","")
    
    # data sensors
    data1 = pd.read_csv("../../Dataset_ECUADOR_2019/"+folder['folder']+"/"+fileName+".csv",
                       delimiter=',', encoding="utf8")
    
    # data from sleep detection
    data2 = pd.read_csv("../../Dataset_ECUADOR_2019/"+folder['folder']+"/Sleep_Detection_"+fileName+".csv",
                       delimiter=',', encoding="utf8")
   
    # merge data
    mergedDS = pd.merge(data1, data2, on='timestamp')
    print(folder['folder']+" "+str(mergedDS.shape[0]))
    # remove unecessary attributes not relevant to sleep detection: foregroundApp,wifi,bluetooth,ble, risk,suburb,municipality,city,town,county
    del mergedDS["foregroundApp"]
    del mergedDS["wifi"]
    del mergedDS["bluetooth"]
    del mergedDS["ble"]
    del mergedDS["risk"]
    del mergedDS["suburb"]
    del mergedDS["municipality"]
    del mergedDS["city"]
    del mergedDS["town"]
    del mergedDS["county"]
    del mergedDS["Unnamed: 0"]
    del mergedDS["activity_y"]
    # rename
    mergedDS.rename(columns = {'activity_x':'activity'}, inplace = True)
    
    # convert merged DF timestamp to datetime
    mergedDS['timestamp_text'] = pd.to_datetime(mergedDS['timestamp'])
    mergedDS['timestamp']  = mergedDS['timestamp_text'].astype(int).div(10**9)
    # time of the day
    #mergedDS['minutes_day'] = mergedDS['timestamp'].hour * 60 + mergedDS['timestamp'].minute
    mergedDS['minutes_day'] = mergedDS.timestamp_text.dt.hour * 60 + mergedDS.timestamp_text.dt.minute
    # initialize times
    mergedDS['sleep_time'] = 0
    mergedDS['wakeup_time'] = 0
    mergedDS['time_sleeping'] = 0
    
    # remove temp information
    #del mergedDS['sleep_time']
    #del mergedDS['wakeup_time']
    #del mergedDS['time_sleeping']
    # replace the place from the class
    
    # remove the outlier (we start the experiment in 1526043855)
    outliers = mergedDS.loc[mergedDS['timestamp'] < 1526043855]
    print("Outliers: ",len(outliers))
    if(len(outliers) > 0):
        print((outliers))
    mergedDS = mergedDS.loc[mergedDS['timestamp'] >= 1526043850]
    # print the guy
    #mergedDS.to_csv(outputFolders+"student_"+folder['folder']+".csv", sep=',', encoding='utf-8', index=False)
    # add in the list
    clientData.append(mergedDS)
    #mergedDS.to_csv("dados2019/student_"+folder['folder']+".csv", sep=',', encoding='utf-8', index=False)
    print("Louded data: ",len(mergedDS))

Loading data
0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs 17993
Outliers:  0
Louded data:  17993
0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA 11561
Outliers:  0
Louded data:  11561
2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0 3383
Outliers:  0
Louded data:  3383
2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys 19389
Outliers:  0
Louded data:  19389
7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA 2753
Outliers:  0
Louded data:  2753
a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4 26567
Outliers:  0
Louded data:  26567
ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc 24534
Outliers:  0
Louded data:  24534
Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U 33903
Outliers:  1
     activity location  distanceHome  showActuation     timestamp  \
3188  Unknown    Other             0          False  1.420070e+09

      time_to_next_alarm  sound  proximity phone_lock  light day_of_week  \
3188                -1.0      0          0     locked      0   Wednesday

                timestamp_text  minutes_day  sleep_time  wakeup_time  \
3188 2015-01-01 00:01:27+00:00            1           0            0

      time_sleeping
3188              0
Louded data:  33902
CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA 26440
Outliers:  0
Louded data:  26440
DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc 24484
Outliers:  0
Louded data:  24484
DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA 1712
Outliers:  0
Louded data:  1712
dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY 26020
Outliers:  0
Louded data:  26020
HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo 25932
Outliers:  0
Louded data:  25932
jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw 31873
Outliers:  0
Louded data:  31873
JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I 23244
Outliers:  0
Louded data:  23244
K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8 19595
Outliers:  0
Louded data:  19595
oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q 21669
Outliers:  0
Louded data:  21669
pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM 33344
Outliers:  0
Louded data:  33344
PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc 1398
Outliers:  0
Louded data:  1398
QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ 22059
Outliers:  0
Louded data:  22059
rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw 23745
Outliers:  0
Louded data:  23745
RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI 32918
Outliers:  0
Louded data:  32918
SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4 12709
Outliers:  0
Louded data:  12709
VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is 15245
Outliers:  0
Louded data:  15245
Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw 2612
Outliers:  0
Louded data:  2612
XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA 17426
Outliers:  0
Louded data:  17426
YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw 19131
Outliers:  0
Louded data:  19131
ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM 59
Outliers:  0
Louded data:  59
ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY 23752
Outliers:  0
Louded data:  23752

In [18]:
print("labeling data")
for index in range(0,len(clientData)):
#for index in [0,1]:
    currentClientData = clientData[index]
    currentFolder = datasets[index]
    
    dataFLabel = pd.read_csv("../data_2019_processed/form/sleep_form_"+currentFolder+"_treated.csv",
                   delimiter=',', encoding="utf8")
    
    # transform the timestamp on datetime
    dataFLabel['timestamp'] = pd.to_datetime(dataFLabel['timestamp'])
    # sleep_time	wakeup_time
    #dataFLabel['sleep_time'] = pd.to_datetime(dataFLabel['sleep_time'])
    
    #dataFLabel['wakeup_time'] = pd.to_datetime(dataFLabel['wakeup_time'])
    
    # initialize other stuff sleep	arousal	valence	dominance	physical_activity	sociability	study
    currentClientData['sleep_time'] = 0
    currentClientData['wakeup_time'] = 0
    currentClientData['sleep'] = 0
    currentClientData['arousal'] = 0
    currentClientData['valence'] = 0
    currentClientData['dominance'] = 0
    currentClientData['physical_activity'] = 0
    currentClientData['sociability'] = 0
    currentClientData['study'] = 0
    
    # add class
    currentClientData["class"] = 'awake'
    
    last_wakeup_time = 0
    # sleep_time	wakeup_time
    for index, labelSet in dataFLabel.iterrows():
        sleep_time = dataFLabel['sleep_time'][index]
        wakeup_time = dataFLabel['wakeup_time'][index]
        
        #condition = (currentClientData['timestamp'] >= sleep_time) & (currentClientData['timestamp'] <= wakeup_time)
        #currentClientData[condition] = currentClientData[condition].apply(lambda x: addKeyWords(x, list_orange))
        
        # replace value
        for indexT, contentT in currentClientData['timestamp'].items():
            # when attributed, stop the process, unless is the last index
            if(contentT > wakeup_time and index < dataFLabel.index[-1]):
                break;
                
            # attribute the sleep class
            if(sleep_time <= contentT) and (contentT <= wakeup_time):
                currentClientData['class'][indexT] = 'asleep'
                
            # only start after the last wake up
            if(last_wakeup_time > contentT):
                # attribute other stuff
                sleep_time_dt = datetime.fromtimestamp(sleep_time, tz = None)     
                wakeup_time_dt = datetime.fromtimestamp(wakeup_time, tz = None)        
                currentClientData['sleep_time'][indexT] = sleep_time_dt.hour * 60 + sleep_time_dt.minute 
                currentClientData['wakeup_time'][indexT] = wakeup_time_dt.hour * 60 + wakeup_time_dt.minute 
                currentClientData['time_sleeping'][indexT] = wakeup_time - sleep_time 
                # data form the form
                currentClientData['sleep'][indexT]      = dataFLabel['sleep'][index]
                currentClientData['arousal'][indexT]    = dataFLabel['arousal'][index]
                currentClientData['valence'][indexT]    = dataFLabel['valence'][index]
                currentClientData['dominance'][indexT]  = dataFLabel['dominance'][index]
                currentClientData['physical_activity'][indexT] =dataFLabel['physical_activity'][index]
                currentClientData['sociability'][indexT] = dataFLabel['sociability'][index]
                currentClientData['study'][indexT]      = dataFLabel['study'][index]
            
        last_wakeup_time = wakeup_time
            
    print(Counter(currentClientData["class"]))

labeling data
Counter({'awake': 15885, 'asleep': 2108})
Counter({'awake': 8695, 'asleep': 2866})
Counter({'awake': 2105, 'asleep': 1278})
Counter({'awake': 16204, 'asleep': 3185})
Counter({'awake': 2345, 'asleep': 408})
Counter({'awake': 22216, 'asleep': 4351})
Counter({'awake': 21273, 'asleep': 3261})
Counter({'awake': 28939, 'asleep': 4963})
Counter({'awake': 20512, 'asleep': 5928})
Counter({'awake': 20357, 'asleep': 4127})
Counter({'awake': 1712})
Counter({'awake': 19617, 'asleep': 6403})
Counter({'awake': 22715, 'asleep': 3217})
Counter({'awake': 26704, 'asleep': 5169})
Counter({'awake': 19434, 'asleep': 3810})
Counter({'awake': 16028, 'asleep': 3567})
Counter({'asleep': 10975, 'awake': 10694})
Counter({'awake': 28477, 'asleep': 4867})
Counter({'awake': 1398})
Counter({'awake': 16615, 'asleep': 5444})
Counter({'awake': 21014, 'asleep': 2731})
Counter({'awake': 25019, 'asleep': 7899})
Counter({'awake': 11508, 'asleep': 1201})
Counter({'awake': 13523, 'asleep': 1722})
Counter({'awake': 1894, 'asleep': 718})
Counter({'awake': 14873, 'asleep': 2553})
Counter({'awake': 13570, 'asleep': 5561})
Counter({'asleep': 36, 'awake': 23})
Counter({'awake': 18915, 'asleep': 4837})

In [20]:
currentClientData

,activity,location,distanceHome,showActuation,timestamp,time_to_next_alarm,sound,proximity,phone_lock,light,...,wakeup_time,time_sleeping,sleep,arousal,valence,dominance,physical_activity,sociability,study,class
0,Unknown,Other,0,False,1.526574e+09,589380000.0,0,5,not locked,168,...,900,28800,4,4,1,2,4,3,4,awake
1,Unknown,University,0,False,1.526574e+09,589320000.0,5533,5,not locked,73,...,900,28800,4,4,1,2,4,3,4,awake
2,Still,University,0,False,1.526574e+09,589260000.0,6348,5,not locked,123,...,900,28800,4,4,1,2,4,3,4,awake
3,Unknown,University,0,False,1.526574e+09,589260000.0,6348,5,not locked,75,...,900,28800,4,4,1,2,4,3,4,awake
4,Still,University,0,False,1.526574e+09,589200000.0,21849,5,not locked,107,...,900,28800,4,4,1,2,4,3,4,awake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23747,Still,House,0,False,1.528892e+09,59999.0,0,5,locked,8,...,0,0,0,0,0,0,0,0,0,awake
23748,Still,House,0,False,1.528892e+09,420000.0,0,5,locked,11,...,0,0,0,0,0,0,0,0,0,awake
23749,Still,House,0,False,1.528892e+09,359999.0,0,5,locked,11,...,0,0,0,0,0,0,0,0,0,awake
23750,Still,House,0,False,1.528892e+09,359999.0,0,5,locked,12,...,0,0,0,0,0,0,0,0,0,awake
23751,Tilting,House,0,False,1.528892e+09,299998.0,0,0,locked,0,...,0,0,0,0,0,0,0,0,0,awake

In [21]:
index

16

In [22]:
np.mean(currentClientData["study"])

2.581003704951162

In [23]:
Counter(currentClientData["class"])

Counter({'awake': 18915, 'asleep': 4837})

In [24]:
dataFLabel

,Unnamed: 0.1,index,Unnamed: 0,sleep_time,wakeup_time,sleep,arousal,valence,dominance,physical_activity,sociability,study,timestamp,time_sleeping,time_sleeping_hs,duplicated
0,0,0,0,1.526592e+09,1.526609e+09,1,2,4,1,1,4,2,2018-05-18 03:22:43+00:00,17100.0,4.750000,0
1,1,1,1,1.526613e+09,1.526642e+09,2,0,1,3,0,0,0,2018-05-18 12:21:12+00:00,28812.0,8.003333,0
2,2,2,2,1.526623e+09,1.526634e+09,2,2,3,3,0,4,3,2018-05-19 03:48:10+00:00,10800.0,3.000000,0
3,3,3,3,1.526794e+09,1.526823e+09,0,0,0,0,0,1,2,2018-05-20 14:39:52+00:00,28800.0,8.000000,0
4,4,4,4,1.526796e+09,1.526875e+09,2,4,4,1,1,2,1,2018-05-21 05:50:36+00:00,79236.0,22.010000,0
5,5,5,5,1.526884e+09,1.526902e+09,4,1,4,2,2,3,3,2018-05-21 15:40:24+00:00,18000.0,5.000000,0
6,6,6,6,1.526963e+09,1.527006e+09,4,4,2,2,3,4,4,2018-05-22 05:16:30+00:00,43200.0,12.000000,0
7,7,9,9,1.527314e+09,1.527350e+09,1,1,4,3,3,4,1,2018-05-26 17:08:10+00:00,36000.0,10.000000,0
8,8,10,10,1.527401e+09,1.527419e+09,4,4,1,2,3,4,0,2018-05-27 15:13:32+00:00,18000.0,5.000000,0
9,9,11,11,1.527487e+09,1.527505e+09,4,4,4,4,3,4,2,2018-05-28 14:54:13+00:00,18000.0,5.000000,0
10,10,12,12,1.527565e+09,1.527588e+09,4,1,3,3,2,3,3,2018-05-29 12:14:24+00:00,23424.0,6.506667,0
11,11,13,13,1.527610e+09,1.527678e+09,4,3,1,1,2,4,3,2018-05-30 12:57:36+00:00,68436.0,19.010000,0
12,12,14,14,1.527746e+09,1.527764e+09,3,4,3,3,3,2,4,2018-05-31 19:53:28+00:00,18000.0,5.000000,0
13,13,15,15,1.527952e+09,1.527962e+09,4,4,4,4,2,4,2,2018-06-02 19:12:45+00:00,10800.0,3.000000,0
14,14,16,16,1.528002e+09,1.528031e+09,3,1,4,4,3,4,0,2018-06-03 17:53:48+00:00,28800.0,8.000000,0
15,15,18,18,1.528020e+09,1.528092e+09,3,2,3,3,4,2,4,2018-06-05 03:54:27+00:00,72027.0,20.007500,0
16,16,20,20,1.528783e+09,1.528812e+09,4,4,1,2,4,3,4,2018-06-12 15:45:58+00:00,28800.0,8.000000,0

In [25]:
currentClientData

,activity,location,distanceHome,showActuation,timestamp,time_to_next_alarm,sound,proximity,phone_lock,light,...,wakeup_time,time_sleeping,sleep,arousal,valence,dominance,physical_activity,sociability,study,class
0,Unknown,Other,0,False,1.526574e+09,589380000.0,0,5,not locked,168,...,900,28800,4,4,1,2,4,3,4,awake
1,Unknown,University,0,False,1.526574e+09,589320000.0,5533,5,not locked,73,...,900,28800,4,4,1,2,4,3,4,awake
2,Still,University,0,False,1.526574e+09,589260000.0,6348,5,not locked,123,...,900,28800,4,4,1,2,4,3,4,awake
3,Unknown,University,0,False,1.526574e+09,589260000.0,6348,5,not locked,75,...,900,28800,4,4,1,2,4,3,4,awake
4,Still,University,0,False,1.526574e+09,589200000.0,21849,5,not locked,107,...,900,28800,4,4,1,2,4,3,4,awake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23747,Still,House,0,False,1.528892e+09,59999.0,0,5,locked,8,...,0,0,0,0,0,0,0,0,0,awake
23748,Still,House,0,False,1.528892e+09,420000.0,0,5,locked,11,...,0,0,0,0,0,0,0,0,0,awake
23749,Still,House,0,False,1.528892e+09,359999.0,0,5,locked,11,...,0,0,0,0,0,0,0,0,0,awake
23750,Still,House,0,False,1.528892e+09,359999.0,0,5,locked,12,...,0,0,0,0,0,0,0,0,0,awake
23751,Tilting,House,0,False,1.528892e+09,299998.0,0,0,locked,0,...,0,0,0,0,0,0,0,0,0,awake

In [26]:
Counter(currentClientData["class"])

Counter({'awake': 18915, 'asleep': 4837})

In [28]:
print("saving data")
for index in range(0,len(clientData)):
#for index in [0,1]:
    currentClientData = clientData[index]
    currentFolder = datasets[index]
    # print
    outputFile = outputFolders+"student_"+currentFolder+".csv"
    print(index,"Saving data on file",outputFile)
    # print the guy
    currentClientData.to_csv(outputFile, sep=',', encoding='utf-8', index=False)

saving data
0 Saving data on file ../data_2019_processed/student_0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs.csv
1 Saving data on file ../data_2019_processed/student_0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA.csv
2 Saving data on file ../data_2019_processed/student_2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0.csv
3 Saving data on file ../data_2019_processed/student_2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys.csv
4 Saving data on file ../data_2019_processed/student_7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA.csv
5 Saving data on file ../data_2019_processed/student_a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4.csv
6 Saving data on file ../data_2019_processed/student_ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc.csv
7 Saving data on file ../data_2019_processed/student_Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U.csv
8 Saving data on file ../data_2019_processed/student_CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA.csv
9 Saving data on file ../data_2019_processed/student_DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc.csv
10 Saving data on file ../data_2019_processed/student_DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA.csv
11 Saving data on file ../data_2019_processed/student_dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY.csv
12 Saving data on file ../data_2019_processed/student_HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo.csv
13 Saving data on file ../data_2019_processed/student_jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw.csv
14 Saving data on file ../data_2019_processed/student_JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I.csv
15 Saving data on file ../data_2019_processed/student_K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8.csv
16 Saving data on file ../data_2019_processed/student_oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q.csv
17 Saving data on file ../data_2019_processed/student_pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM.csv
18 Saving data on file ../data_2019_processed/student_PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc.csv
19 Saving data on file ../data_2019_processed/student_QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ.csv
20 Saving data on file ../data_2019_processed/student_rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw.csv
21 Saving data on file ../data_2019_processed/student_RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI.csv
22 Saving data on file ../data_2019_processed/student_SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4.csv
23 Saving data on file ../data_2019_processed/student_VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is.csv
24 Saving data on file ../data_2019_processed/student_Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw.csv
25 Saving data on file ../data_2019_processed/student_XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA.csv
26 Saving data on file ../data_2019_processed/student_YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw.csv
27 Saving data on file ../data_2019_processed/student_ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM.csv
28 Saving data on file ../data_2019_processed/student_ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY.csv

In [31]:
print("Join all files")
# inicia com o primeiro
allData = clientData[0]
for index in range(1,len(clientData)):
#for index in [0,1]:
    currentClientData = clientData[index]
    
    allData = pd.concat([allData,currentClientData], ignore_index=True)
    
    
# 
print("total of entries:",len(allData))

Join all files
total of entries: 545449

# Weekly Division

In [33]:
# identify how many weeks the data has
GlobalMaxValueFromTimestamp = allData["timestamp"].max()
GlobalMinvalueFromTimestamp = allData["timestamp"].min()

print(GlobalMaxValueFromTimestamp,GlobalMinvalueFromTimestamp)

experimentTime = GlobalMaxValueFromTimestamp - GlobalMinvalueFromTimestamp
minuts = experimentTime / (60)
hours = minuts / (60)
days  = hours / 24
weeks = days / 7

print(experimentTime)
print(hours,days,weeks)

1528895841.0 1526047455.0
2848386.0
791.2183333333334 32.96743055555556 4.709632936507937

In [34]:
WeekTime = 60*60*24*7 # min, hour, day, week

print("Week in seconds:",WeekTime)
print()


experimentTime / WeekTime

numberOfWeeks = 4 # each week will have the WeekTime, but the rest not

for i in range(0,numberOfWeeks):
    beginValueWeek = GlobalMinvalueFromTimestamp + (WeekTime*i)
    endValueWeek = GlobalMinvalueFromTimestamp + (WeekTime*(i+1))
    
    if(i == (numberOfWeeks-1)):
        endValueWeek = GlobalMaxValueFromTimestamp
    
    print("week:", i)
    
    print("Begin/end: ",beginValueWeek,endValueWeek)
    amountX = endValueWeek - beginValueWeek
    amountX = amountX / WeekTime
    print("Amount: ",amountX)
    
    print("Creating folder")
    folderName = outputFolders + "w" + str(i)
    isExist = os.path.exists(folderName)
    if not isExist:
        # Create a new directory because it does not exist
        os.makedirs(folderName)
        print("The directory is created!")
    else:
        print("The directory exists!")
    print()

Week in seconds: 604800

week: 0
Begin/end:  1526047455.0 1526652255.0
Amount:  1.0
Creating folder
The directory exists!

week: 1
Begin/end:  1526652255.0 1527257055.0
Amount:  1.0
Creating folder
The directory exists!

week: 2
Begin/end:  1527257055.0 1527861855.0
Amount:  1.0
Creating folder
The directory exists!

week: 3
Begin/end:  1527861855.0 1528895841.0
Amount:  1.7096329365079366
Creating folder
The directory exists!

In [35]:
numerOfWeeks = 4 # each week will have the WeekTime, but the rest not

for index in range(0, len(clientData)):
    client = clientData[index]
    print("Client:",index)
    maxValueFromTimestamp = client["timestamp"].max()
    minvalueFromTimestamp = client["timestamp"].min()

    print(maxValueFromTimestamp,minvalueFromTimestamp)

    experimentTime = maxValueFromTimestamp - minvalueFromTimestamp
    minuts = experimentTime / (60)
    hours = minuts / (60)
    days  = hours / 24
    weeks = days / 7

    print(experimentTime)
    print(hours,days,weeks)
    print()

Client: 0
1528895841.0 1526394045.0
2501796.0
694.9433333333333 28.95597222222222 4.13656746031746

Client: 1
1528770554.0 1526418834.0
2351720.0
653.2555555555556 27.21898148148148 3.888425925925926

Client: 2
1528759478.0 1526394086.0
2365392.0
657.0533333333333 27.37722222222222 3.9110317460317456

Client: 3
1528399154.0 1526145830.0
2253324.0
625.9233333333334 26.080138888888893 3.7257341269841278

Client: 4
1527609936.0 1526218894.0
1391042.0
386.40055555555557 16.10002314814815 2.300003306878307

Client: 5
1528809555.0 1526155481.0
2654074.0
737.2427777777777 30.718449074074073 4.388349867724868

Client: 6
1528847269.0 1526393802.0
2453467.0
681.5186111111111 28.396608796296295 4.0566583994709

Client: 7
1528805813.0 1526330077.0
2475736.0
687.7044444444444 28.654351851851853 4.0934788359788365

Client: 8
1528850779.0 1526361153.0
2489626.0
691.5627777777778 28.81511574074074 4.116445105820106

Client: 9
1528828118.0 1526302511.0
2525607.0
701.5575 29.2315625 4.1759375

Client: 10
1528663507.0 1526571032.0
2092475.0
581.2430555555555 24.21846064814815 3.4597800925925926

Client: 11
1528805930.0 1526332845.0
2473085.0
686.9680555555556 28.623668981481483 4.089095568783069

Client: 12
1528887041.0 1526329346.0
2557695.0
710.4708333333333 29.602951388888886 4.228993055555555

Client: 13
1528868748.0 1526393979.0
2474769.0
687.4358333333333 28.643159722222222 4.091879960317461

Client: 14
1528820220.0 1526324244.0
2495976.0
693.3266666666666 28.888611111111107 4.126944444444444

Client: 15
1528726910.0 1526047455.0
2679455.0
744.2930555555556 31.01221064814815 4.4303158068783075

Client: 16
1528830409.0 1526320685.0
2509724.0
697.1455555555555 29.047731481481478 4.1496759259259255

Client: 17
1528811737.0 1526340777.0
2470960.0
686.3777777777777 28.59907407407407 4.08558201058201

Client: 18
1528765800.0 1526352417.0
2413383.0
670.3841666666667 27.932673611111113 3.9903819444444446

Client: 19
1528692743.0 1526386623.0
2306120.0
640.588888888889 26.691203703703707 3.813029100529101

Client: 20
1528683507.0 1526314568.0
2368939.0
658.0386111111111 27.418275462962963 3.9168964947089946

Client: 21
1528807531.0 1526094429.0
2713102.0
753.6394444444445 31.401643518518522 4.485949074074075

Client: 22
1528810173.0 1526577724.0
2232449.0
620.1247222222222 25.838530092592592 3.6912185846560845

Client: 23
1528745204.0 1526148380.0
2596824.0
721.34 30.055833333333336 4.293690476190476

Client: 24
1528429665.0 1526318087.0
2111578.0
586.5494444444445 24.439560185185186 3.491365740740741

Client: 25
1528812444.0 1526316727.0
2495717.0
693.2547222222222 28.885613425925925 4.126516203703703

Client: 26
1528808071.0 1526475263.0
2332808.0
648.0022222222221 27.00009259259259 3.857156084656084

Client: 27
1528303633.0 1526393820.0
1909813.0
530.5036111111111 22.10431712962963 3.1577595899470903

Client: 28
1528892408.0 1526574094.0
2318314.0
643.9761111111111 26.832337962962963 3.833191137566138

In [36]:
trainAmount = []

for i in range(0,numberOfWeeks):
    trainAmount.append(0)

for index in range(0, len(clientData)):
    client = clientData[index]
    print("Client:",index)
    
    for i in range(0,numberOfWeeks):
        beginValueWeek = GlobalMinvalueFromTimestamp + (WeekTime*i)
        endValueWeek = GlobalMinvalueFromTimestamp + (WeekTime*(i+1))


        if(i == (numberOfWeeks-1)):
            endValueWeek = GlobalMaxValueFromTimestamp

        
        amountX = endValueWeek - beginValueWeek
        amountX = amountX / WeekTime
        print("week:", i," - Begin/end: ",beginValueWeek,endValueWeek)
        print("Amount rate: ",amountX)
        
        
        selectedData = client.loc[client['timestamp'] >= beginValueWeek]
        selectedData = selectedData.loc[selectedData['timestamp'] <= endValueWeek]

        print("Amount: ",len(selectedData))
        print(Counter(selectedData['class']))
        
        #print()
        trainAmount[i] = trainAmount[i] + len(selectedData)

    print()

Client: 0
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  2409
Counter({'awake': 1629, 'asleep': 780})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  4390
Counter({'awake': 4064, 'asleep': 326})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  4534
Counter({'awake': 4246, 'asleep': 288})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  6660
Counter({'awake': 5946, 'asleep': 714})

Client: 1
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  1614
Counter({'asleep': 838, 'awake': 776})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  2586
Counter({'awake': 2018, 'asleep': 568})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  3610
Counter({'awake': 3299, 'asleep': 311})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  3751
Counter({'awake': 2602, 'asleep': 1149})

Client: 2
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  339
Counter({'awake': 225, 'asleep': 114})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  1410
Counter({'asleep': 798, 'awake': 612})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  248
Counter({'awake': 160, 'asleep': 88})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  1386
Counter({'awake': 1108, 'asleep': 278})

Client: 3
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  2685
Counter({'awake': 2387, 'asleep': 298})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  5183
Counter({'awake': 4691, 'asleep': 492})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  6472
Counter({'awake': 5497, 'asleep': 975})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  5049
Counter({'awake': 3629, 'asleep': 1420})

Client: 4
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  859
Counter({'awake': 859})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  1308
Counter({'awake': 1094, 'asleep': 214})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  586
Counter({'awake': 392, 'asleep': 194})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  0
Counter()

Client: 5
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  4267
Counter({'awake': 3343, 'asleep': 924})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  6554
Counter({'awake': 4319, 'asleep': 2235})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  7055
Counter({'awake': 6703, 'asleep': 352})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  8691
Counter({'awake': 7851, 'asleep': 840})

Client: 6
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  2445
Counter({'awake': 1703, 'asleep': 742})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  6481
Counter({'awake': 5721, 'asleep': 760})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  6105
Counter({'awake': 5684, 'asleep': 421})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  9503
Counter({'awake': 8165, 'asleep': 1338})

Client: 7
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  4026
Counter({'awake': 2885, 'asleep': 1141})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  8808
Counter({'awake': 7635, 'asleep': 1173})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  8560
Counter({'awake': 7654, 'asleep': 906})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  12508
Counter({'awake': 10765, 'asleep': 1743})

Client: 8
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  3342
Counter({'awake': 2289, 'asleep': 1053})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  6752
Counter({'awake': 4522, 'asleep': 2230})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  5735
Counter({'awake': 4864, 'asleep': 871})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  10611
Counter({'awake': 8837, 'asleep': 1774})

Client: 9
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  2792
Counter({'awake': 2237, 'asleep': 555})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  7007
Counter({'awake': 6115, 'asleep': 892})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  8075
Counter({'awake': 5991, 'asleep': 2084})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  6610
Counter({'awake': 6014, 'asleep': 596})

Client: 10
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  8
Counter({'awake': 8})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  3
Counter({'awake': 3})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  0
Counter()
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  1701
Counter({'awake': 1701})

Client: 11
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  3702
Counter({'awake': 2380, 'asleep': 1322})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  6858
Counter({'awake': 5218, 'asleep': 1640})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  7401
Counter({'awake': 5925, 'asleep': 1476})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  8059
Counter({'awake': 6094, 'asleep': 1965})

Client: 12
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  2911
Counter({'awake': 2281, 'asleep': 630})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  6717
Counter({'awake': 5764, 'asleep': 953})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  6524
Counter({'awake': 5770, 'asleep': 754})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  9780
Counter({'awake': 8900, 'asleep': 880})

Client: 13
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  768
Counter({'awake': 765, 'asleep': 3})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  3559
Counter({'awake': 2820, 'asleep': 739})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  8549
Counter({'awake': 7052, 'asleep': 1497})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  18997
Counter({'awake': 16067, 'asleep': 2930})

Client: 14
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  3608
Counter({'awake': 3199, 'asleep': 409})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  7172
Counter({'awake': 5861, 'asleep': 1311})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  5336
Counter({'awake': 4716, 'asleep': 620})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  7128
Counter({'awake': 5658, 'asleep': 1470})

Client: 15
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  5265
Counter({'awake': 3725, 'asleep': 1540})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  5398
Counter({'awake': 4474, 'asleep': 924})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  2817
Counter({'awake': 2684, 'asleep': 133})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  6115
Counter({'awake': 5145, 'asleep': 970})

Client: 16
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  4777
Counter({'awake': 2749, 'asleep': 2028})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  6106
Counter({'asleep': 3957, 'awake': 2149})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  3178
Counter({'awake': 2100, 'asleep': 1078})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  7608
Counter({'asleep': 3912, 'awake': 3696})

Client: 17
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  4863
Counter({'awake': 4334, 'asleep': 529})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  9588
Counter({'awake': 7934, 'asleep': 1654})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  9367
Counter({'awake': 7620, 'asleep': 1747})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  9526
Counter({'awake': 8589, 'asleep': 937})

Client: 18
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  607
Counter({'awake': 607})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  330
Counter({'awake': 330})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  126
Counter({'awake': 126})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  335
Counter({'awake': 335})

Client: 19
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  3731
Counter({'awake': 2735, 'asleep': 996})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  4531
Counter({'awake': 4211, 'asleep': 320})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  5869
Counter({'awake': 3548, 'asleep': 2321})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  7928
Counter({'awake': 6121, 'asleep': 1807})

Client: 20
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  3088
Counter({'awake': 2534, 'asleep': 554})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  8087
Counter({'awake': 7085, 'asleep': 1002})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  3075
Counter({'awake': 2725, 'asleep': 350})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  9495
Counter({'awake': 8670, 'asleep': 825})

Client: 21
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  7573
Counter({'awake': 5377, 'asleep': 2196})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  7667
Counter({'awake': 4885, 'asleep': 2782})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  5701
Counter({'awake': 3705, 'asleep': 1996})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  11977
Counter({'awake': 11052, 'asleep': 925})

Client: 22
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  2
Counter({'awake': 2})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  3268
Counter({'awake': 2776, 'asleep': 492})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  3847
Counter({'awake': 3403, 'asleep': 444})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  5592
Counter({'awake': 5327, 'asleep': 265})

Client: 23
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  3611
Counter({'awake': 3004, 'asleep': 607})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  3012
Counter({'awake': 2551, 'asleep': 461})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  3798
Counter({'awake': 3354, 'asleep': 444})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  4824
Counter({'awake': 4614, 'asleep': 210})

Client: 24
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  1374
Counter({'awake': 863, 'asleep': 511})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  421
Counter({'awake': 240, 'asleep': 181})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  391
Counter({'awake': 377, 'asleep': 14})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  426
Counter({'awake': 414, 'asleep': 12})

Client: 25
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  2704
Counter({'awake': 2266, 'asleep': 438})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  4408
Counter({'awake': 3839, 'asleep': 569})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  5005
Counter({'awake': 4357, 'asleep': 648})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  5309
Counter({'awake': 4411, 'asleep': 898})

Client: 26
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  263
Counter({'awake': 132, 'asleep': 131})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  377
Counter({'awake': 333, 'asleep': 44})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  3580
Counter({'awake': 2955, 'asleep': 625})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  14911
Counter({'awake': 10150, 'asleep': 4761})

Client: 27
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  1
Counter({'awake': 1})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  0
Counter()
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  0
Counter()
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  58
Counter({'asleep': 36, 'awake': 22})

Client: 28
week: 0  - Begin/end:  1526047455.0 1526652255.0
Amount rate:  1.0
Amount:  1331
Counter({'asleep': 870, 'awake': 461})
week: 1  - Begin/end:  1526652255.0 1527257055.0
Amount rate:  1.0
Amount:  7672
Counter({'awake': 5626, 'asleep': 2046})
week: 2  - Begin/end:  1527257055.0 1527861855.0
Amount rate:  1.0
Amount:  5518
Counter({'awake': 3991, 'asleep': 1527})
week: 3  - Begin/end:  1527861855.0 1528895841.0
Amount rate:  1.7096329365079366
Amount:  9231
Counter({'awake': 8837, 'asleep': 394})

In [59]:
trainAmount = []

for i in range(0,numberOfWeeks):
    trainAmount.append(0)

for index in range(0, len(clientData)):
    client = clientData[index]
    clientDataName = datasets[index]
    print("Client:",index)
    
    for i in range(0,numberOfWeeks):
        beginValueWeek = GlobalMinvalueFromTimestamp + (WeekTime*i)
        endValueWeek = GlobalMinvalueFromTimestamp + (WeekTime*(i+1))


        if(i == (numberOfWeeks-1)):
            endValueWeek = GlobalMaxValueFromTimestamp

        
        amountX = endValueWeek - beginValueWeek
        amountX = amountX / WeekTime
        print("week:", i," - Begin/end: ",beginValueWeek,endValueWeek)
        print("Amount rate: ",amountX)
        
        
        selectedData = client.loc[client['timestamp'] >= beginValueWeek]
        selectedData = selectedData.loc[selectedData['timestamp'] <= endValueWeek]

        print("Amount: ",len(selectedData))
        print(Counter(selectedData['class']))
        
        #print()
        trainAmount[i] = trainAmount[i] + len(selectedData)
        
        folderName = outputFolders + "w" + str(i)
        selectedData.to_csv(folderName+"/student_"+clientDataName+".csv", sep=',', encoding='utf-8', index=False)
    print()

Client: 0
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  2409
Counter({'awake': 1732, 'asleep': 677})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  4390
Counter({'awake': 4174, 'asleep': 216})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  4534
Counter({'awake': 4338, 'asleep': 196})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  6660
Counter({'awake': 6097, 'asleep': 563})

Client: 1
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  1614
Counter({'awake': 828, 'asleep': 786})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  2586
Counter({'awake': 1694, 'asleep': 892})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  3610
Counter({'awake': 3285, 'asleep': 325})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  3751
Counter({'awake': 2351, 'asleep': 1400})

Client: 2
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  339
Counter({'awake': 234, 'asleep': 105})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  1410
Counter({'asleep': 851, 'awake': 559})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  248
Counter({'awake': 160, 'asleep': 88})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  1386
Counter({'awake': 1111, 'asleep': 275})

Client: 3
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  2685
Counter({'awake': 2468, 'asleep': 217})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  5183
Counter({'awake': 4769, 'asleep': 414})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  6472
Counter({'awake': 5553, 'asleep': 919})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  5049
Counter({'awake': 3796, 'asleep': 1253})

Client: 4
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  859
Counter({'awake': 859})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  1308
Counter({'awake': 1175, 'asleep': 133})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  586
Counter({'awake': 392, 'asleep': 194})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  0
Counter()

Client: 5
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  4267
Counter({'awake': 3240, 'asleep': 1027})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  6554
Counter({'awake': 4360, 'asleep': 2194})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  7055
Counter({'awake': 6820, 'asleep': 235})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  8691
Counter({'awake': 7821, 'asleep': 870})

Client: 6
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  2445
Counter({'awake': 1723, 'asleep': 722})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  6481
Counter({'awake': 5863, 'asleep': 618})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  6105
Counter({'awake': 5742, 'asleep': 363})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  9503
Counter({'awake': 8138, 'asleep': 1365})

Client: 7
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  4026
Counter({'awake': 2819, 'asleep': 1207})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  8808
Counter({'awake': 7814, 'asleep': 994})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  8560
Counter({'awake': 7764, 'asleep': 796})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  12508
Counter({'awake': 11086, 'asleep': 1422})

Client: 8
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  3342
Counter({'awake': 2188, 'asleep': 1154})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  6752
Counter({'awake': 4583, 'asleep': 2169})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  5735
Counter({'awake': 4841, 'asleep': 894})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  10611
Counter({'awake': 8722, 'asleep': 1889})

Client: 9
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  2792
Counter({'awake': 2412, 'asleep': 380})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  7007
Counter({'awake': 6396, 'asleep': 611})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  8075
Counter({'awake': 6166, 'asleep': 1909})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  6610
Counter({'awake': 6137, 'asleep': 473})

Client: 10
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  8
Counter({'awake': 8})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  3
Counter({'awake': 3})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  0
Counter()
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  1701
Counter({'awake': 1701})

Client: 11
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  3702
Counter({'awake': 2545, 'asleep': 1157})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  6858
Counter({'awake': 5108, 'asleep': 1750})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  7401
Counter({'awake': 6030, 'asleep': 1371})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  8059
Counter({'awake': 6161, 'asleep': 1898})

Client: 12
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  2911
Counter({'awake': 2222, 'asleep': 689})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  6717
Counter({'awake': 5793, 'asleep': 924})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  6524
Counter({'awake': 5783, 'asleep': 741})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  9780
Counter({'awake': 8880, 'asleep': 900})

Client: 13
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  768
Counter({'awake': 768})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  3559
Counter({'awake': 2907, 'asleep': 652})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  8549
Counter({'awake': 7137, 'asleep': 1412})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  18997
Counter({'awake': 15997, 'asleep': 3000})

Client: 14
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  3608
Counter({'awake': 3283, 'asleep': 325})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  7172
Counter({'awake': 6069, 'asleep': 1103})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  5336
Counter({'awake': 4797, 'asleep': 539})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  7128
Counter({'awake': 5851, 'asleep': 1277})

Client: 15
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  5265
Counter({'awake': 3688, 'asleep': 1577})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  5398
Counter({'awake': 4527, 'asleep': 871})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  2817
Counter({'awake': 2696, 'asleep': 121})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  6115
Counter({'awake': 5075, 'asleep': 1040})

Client: 16
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  4777
Counter({'awake': 2791, 'asleep': 1986})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  6106
Counter({'asleep': 4060, 'awake': 2046})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  3178
Counter({'awake': 2107, 'asleep': 1071})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  7608
Counter({'asleep': 3989, 'awake': 3619})

Client: 17
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  4863
Counter({'awake': 4377, 'asleep': 486})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  9588
Counter({'awake': 7966, 'asleep': 1622})

week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  9367
Counter({'awake': 7656, 'asleep': 1711})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  9526
Counter({'awake': 8625, 'asleep': 901})

Client: 18
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  607
Counter({'awake': 607})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  330
Counter({'awake': 330})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  126
Counter({'awake': 126})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  335
Counter({'awake': 335})

Client: 19
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  3731
Counter({'awake': 2895, 'asleep': 836})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  4531
Counter({'awake': 4256, 'asleep': 275})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  5869
Counter({'awake': 3648, 'asleep': 2221})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  7928
Counter({'awake': 6329, 'asleep': 1599})

Client: 20
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  3088
Counter({'awake': 2597, 'asleep': 491})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  8087
Counter({'awake': 7127, 'asleep': 960})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  3075
Counter({'awake': 2737, 'asleep': 338})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  9495
Counter({'awake': 8790, 'asleep': 705})

Client: 21
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  7573
Counter({'awake': 5747, 'asleep': 1826})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  7667
Counter({'awake': 4948, 'asleep': 2719})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  5701
Counter({'awake': 3840, 'asleep': 1861})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  11977
Counter({'awake': 11052, 'asleep': 925})

Client: 22
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  2
Counter({'awake': 2})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  3268
Counter({'awake': 2771, 'asleep': 497})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  3847
Counter({'awake': 3637, 'asleep': 210})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  5592
Counter({'awake': 5406, 'asleep': 186})

Client: 23
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  3611
Counter({'awake': 3199, 'asleep': 412})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  3012
Counter({'awake': 2539, 'asleep': 473})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  3798
Counter({'awake': 3297, 'asleep': 501})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  4824
Counter({'awake': 4646, 'asleep': 178})

Client: 24
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  1374
Counter({'awake': 823, 'asleep': 551})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  421
Counter({'awake': 257, 'asleep': 164})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  391
Counter({'awake': 377, 'asleep': 14})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  426
Counter({'awake': 414, 'asleep': 12})

Client: 25
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  2704
Counter({'awake': 2314, 'asleep': 390})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  4408
Counter({'awake': 3833, 'asleep': 575})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  5005
Counter({'awake': 4342, 'asleep': 663})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  5309
Counter({'awake': 4560, 'asleep': 749})

Client: 26
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  263
Counter({'awake': 132, 'asleep': 131})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  377
Counter({'awake': 344, 'asleep': 33})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  3580
Counter({'awake': 3012, 'asleep': 568})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  14911
Counter({'awake': 10080, 'asleep': 4831})

Client: 27
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  1
Counter({'awake': 1})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  0
Counter()
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  0
Counter()
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  58
Counter({'asleep': 36, 'awake': 22})

Client: 28
week: 0  - Begin/end:  1526043855 1526648655
Amount rate:  1.0
Amount:  1331
Counter({'asleep': 905, 'awake': 426})
week: 1  - Begin/end:  1526648655 1527253455
Amount rate:  1.0
Amount:  7672
Counter({'awake': 5530, 'asleep': 2142})
week: 2  - Begin/end:  1527253455 1527858255
Amount rate:  1.0
Amount:  5518
Counter({'awake': 4063, 'asleep': 1455})
week: 3  - Begin/end:  1527858255 1528892241
Amount rate:  1.7096329365079366
Amount:  9231
Counter({'awake': 8838, 'asleep': 393})

In [37]:
for weekAmount in trainAmount:
    print(weekAmount)

74965
135653
131062
203769

In [38]:
train = np.sum(trainAmount[0:3])
test = trainAmount[3]
total = train + trainAmount[3]
perTrain = (100/total * train)

print("Train",train)
print("Test",test)
print("Total",total)
print()
print("Train(%)",perTrain)
print("Test(%) ",(100-perTrain))

Train 341680
Test 203769
Total 545449

Train(%) 62.64197019336363
Test(%)  37.35802980663637

In [53]:
train = np.sum(trainAmount[0:3])
test = trainAmount[3]
total = train + trainAmount[3]
perTrain = (100/total * train)

print("Train",train)
print("Test",test)
print("Total",total)
print()
print("Train(%)",perTrain)
print("Test(%) ",(100-perTrain))

Train 341680
Test 203769
Total 545449

Train(%) 62.64197019336363
Test(%)  37.35802980663637