In [1]:
#!pip install pandas

# Gather all data

In [2]:
import csv
import json
import pandas as pd
from datetime import datetime
import numpy as np
from collections import Counter
inputFolders = "../data_2019_processed/"
outputFolders = "../data_2019_processed/train/"

In [3]:
# Dataframe of all datasets
# initialize list of lists
dsTrain =  [['0Jf4TH9Zzse0Z1Jjh7SnTOe2MMzeSnFi7feTnkG6vgs'],
            ['0tdmm6rwW3KquQ73ATYYJ5JkpMtvbppJ0VzA2GExdA'], 
            ['2cyV53lVyUtlMj0BRwilEWtYJwUiviYoL48cZBPBq0'], 
            ['2J22RukYnEbKTk7t+iUVDBkorcyL5NKN6TrLe89ys'], 
            #['5FLZBTVAPwdq9QezHE2sVCJIs7p+r6mCemA2gp9jATk'], #does not have the file
            ['7EYF5I04EVqisUJCVNHlqn77UAuOmwL2Dahxd3cA'], 
            ['a9Qgj8ENWrHvl9QqlXcIPKmyGMKgbfHk9Dbqon1HQP4'], 
            ['ae4JJBZDycEcY8McJF+3BxyvZ1619y03BNdCxzpZTc'], 
            ['Ch3u5Oaz96VSrQbf0z31X6jEIbeIekkC0mwPzCdeJ1U'], 
            ['CH8f0yZkZL13zWuE9ks1CkVJRVrr+jsGdUXHrZ6YeA'], 
            ['DHO1K4jgiwZJOfQTrxvKE2vn7hkjamigroGD5IaeRc'], 
            ['DHPqzSqSttiba1L3BD1cptNJPjSxZ8rXxF9mY3za6WA'], 
            ['dQEFscjqnIlug8Tgq97JohhSQPG2DEOWJqS86wCrcY'], 
            ['HFvs2CohmhHte+AaCzFasjzegGzxZKPhkrX23iI6Xo'], 
            ['jgB9E8v3Z6PKdTRTCMAijBllA9YEMtrmHbe4qsbmJWw'], 
            ['JkY++R7E8myldLN3on6iQ78Ee78zCbrLuggfwGju3I'], 
            ['K4SLohf+TN1Ak8Dn8iE3Lme7rEMPISfppB2sXfHX8'], 
            ['oGaWetJJJEWHuvYdWYo826SQxfhCExVVQ2da8LE1Y7Q'], 
            ['pyt24oiDAHsmgWMvkFKz2fn2pwcHiXchd6KchLM'], 
            #['PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc'], 
            ['QUNCATForxzK0HHw46LrGOMWh0eVA8Y5XWEiUXX+cQ'], 
            #['rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw'], 
            #['RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI'], 
            ['SH3kQeyd5volraxw8vOyhlowNqWBPr1IJ9URNXUL4']] 
            #['VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is'], 
            #['Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw'], 
            #['XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA'], 
            #['YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw'], 
            #['ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM'], 
            #['ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']]


# Create the pandas DataFrame
folders = pd.DataFrame(dsTrain, columns=['folder'])

#folders

# Data pre-processing Train

In [4]:
allData = pd.DataFrame()
for indexFolder, folder in folders.iterrows():

    dataFLabel = pd.read_csv(inputFolders+"student_"+folder['folder']+".csv",
                   delimiter=',', encoding="utf8")
    # print the guy
    dataFLabel.to_csv(outputFolders+"student_"+folder['folder']+".csv", sep=',', encoding='utf-8', index=False)
    #mergedDS.to_csv("dados2019/student_"+folder['folder']+".csv", sep=',', encoding='utf-8', index=False)
    print(Counter(dataFLabel['class']))
    # merge the data set if has both classes
    if('asleep' in Counter(dataFLabel['class'])):
        print("concating")
        if(allData.empty):
            allData = dataFLabel
        else:
            #allData = allData.append(mergedDS, ignore_index=True)
            allData = pd.concat([allData, dataFLabel])
        
# print all
allData.to_csv(outputFolders+"allData.csv", sep=',', encoding='utf-8', index=False)
#allData.to_csv("dados2019/allData.csv", sep=',', encoding='utf-8', index=False)

Counter({'awake': 16341, 'asleep': 1652})
concating
Counter({'awake': 8158, 'asleep': 3403})
concating
Counter({'awake': 2064, 'asleep': 1319})
concating
Counter({'awake': 16586, 'asleep': 2803})
concating
Counter({'awake': 2426, 'asleep': 327})
concating
Counter({'awake': 22241, 'asleep': 4326})
concating
Counter({'awake': 21466, 'asleep': 3068})
concating
Counter({'awake': 29457, 'asleep': 4445})
concating
Counter({'awake': 20334, 'asleep': 6106})
concating
Counter({'awake': 21111, 'asleep': 3373})
concating
Counter({'awake': 1712})
Counter({'awake': 19844, 'asleep': 6176})
concating
Counter({'awake': 22584, 'asleep': 3348})
concating
Counter({'awake': 26809, 'asleep': 5064})
concating
Counter({'awake': 20000, 'asleep': 3244})
concating
Counter({'awake': 15986, 'asleep': 3609})
concating
Counter({'asleep': 10967, 'awake': 10702})
concating
Counter({'awake': 28624, 'asleep': 4720})
concating
Counter({'awake': 17128, 'asleep': 4931})
concating
Counter({'awake': 11732, 'asleep': 977})
concating

In [5]:
allData

,activity,location,distanceHome,showActuation,timestamp,time_to_next_alarm,sound,proximity,phone_lock,light,day_of_week,class,timestamp2,minutes_day,sleep_time,wakeup_time,time_sleeping
0,Unknown,Other,0,False,2018-05-15 14:20:45,594000000.0,0,5,not locked,37,Tuesday,awake,1526390445,860,1020,660,64808
1,Unknown,Other,0,False,2018-05-15 14:20:45,594000000.0,0,5,not locked,37,Tuesday,awake,1526390445,860,1020,660,64808
2,Still,University,0,False,2018-05-15 14:21:15,593940000.0,5517,5,not locked,35,Tuesday,awake,1526390475,861,1020,660,64808
3,Still,University,0,False,2018-05-15 14:21:45,593940000.0,5517,5,not locked,307,Tuesday,awake,1526390505,861,1020,660,64808
4,Still,University,0,False,2018-05-15 14:22:15,593880000.0,5809,5,not locked,42,Tuesday,awake,1526390535,862,1020,660,64808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12704,Still,House,0,False,2018-06-12 13:11:39,600540000.0,2466,5,locked,0,Tuesday,awake,1528805499,791,0,0,0
12705,Still,House,0,False,2018-06-12 13:12:09,600540000.0,2466,5,locked,0,Tuesday,awake,1528805529,792,0,0,0
12706,Still,House,0,False,2018-06-12 13:13:37,600480000.0,3708,5,locked,114,Tuesday,awake,1528805617,793,0,0,0
12707,Unknown,House,0,False,2018-06-12 13:14:07,600420000.0,20080,0,not locked,0,Tuesday,awake,1528805647,794,0,0,0
12708,Still,Other,0,False,2018-06-12 13:29:33,599460000.0,8710,0,locked,1,Tuesday,awake,1528806573,809,0,0,0

# Data pre-processing Test

In [6]:
outputFolders = "../data_2019_processed/test/"

dsTest   = [['PZCf1nfvhR+6fk+7+sPNMYOgb8BAMmtQtfoRS83Suc'], 
            ['rIl2UK9+bQ+tzpFdbJAdbBxEa5GbgrgC030yEaENLw'], 
            ['RoBW3cDOO9wWRMPO2twQff83MPc+OXn6gJ+a1DafreI'], 
            ['VVpwFNMrEglveh6MDN8lrRzTy5OwzglD4FURfM4A2is'], 
            ['Wa1mcNmbh66S7VS6GIzyfCFMD3SGhbtDQyFP1ywJEsw'], 
            ['XCKRE0BWRHxfP1kZIihgtT+jUjSp2GE8v5ZlhcIhVmA'], 
            ['YI5Y79K6GXqAUoGP6PNyII8WKlAoel4urDxWSVVOvBw'], 
            ['ypklj+8GJ15rOIH1lpKQtFJOuK+VdvyCuBPqhY3aoM'], 
            ['ZSsAZ0Pq+MCqFrnjsRFn5Ua09pMCVaOV9c8ZuYb7XQY']]

# Create the pandas DataFrame
folders = pd.DataFrame(dsTest, columns=['folder'])

#folders

In [7]:
allData = pd.DataFrame()
for indexFolder, folder in folders.iterrows():

    dataFLabel = pd.read_csv(inputFolders+"student_"+folder['folder']+".csv",
                   delimiter=',', encoding="utf8")
    # print the guy
    dataFLabel.to_csv(outputFolders+"student_"+folder['folder']+".csv", sep=',', encoding='utf-8', index=False)
    #mergedDS.to_csv("dados2019/student_"+folder['folder']+".csv", sep=',', encoding='utf-8', index=False)
    print(Counter(dataFLabel['class']))
    # merge the data set if has both classes
    if('asleep' in Counter(dataFLabel['class'])):
        print("concating")
        if(allData.empty):
            allData = dataFLabel
        else:
            #allData = allData.append(mergedDS, ignore_index=True)
            allData = pd.concat([allData, dataFLabel])
        
# print all
allData.to_csv(outputFolders+"allData.csv", sep=',', encoding='utf-8', index=False)
#allData.to_csv("dados2019/allData.csv", sep=',', encoding='utf-8', index=False)

Counter({'awake': 1398})
Counter({'awake': 21194, 'asleep': 2551})
concating
Counter({'awake': 25586, 'asleep': 7332})
concating
Counter({'awake': 13681, 'asleep': 1564})
concating
Counter({'awake': 1871, 'asleep': 741})
concating
Counter({'awake': 15049, 'asleep': 2377})
concating
Counter({'awake': 13568, 'asleep': 5563})
concating
Counter({'asleep': 36, 'awake': 23})
concating
Counter({'awake': 18781, 'asleep': 4971})
concating

In [8]:
allData

,activity,location,distanceHome,showActuation,timestamp,time_to_next_alarm,sound,proximity,phone_lock,light,day_of_week,class,timestamp2,minutes_day,sleep_time,wakeup_time,time_sleeping
0,Exercise,House,0,False,2018-05-14 16:16:08,-1.0,32767,8,not locked,0,Monday,awake,1526310968,976,180,600,25235
1,Still,House,0,False,2018-05-14 16:17:39,-1.0,19335,0,locked,1,Monday,awake,1526311059,977,180,600,25235
2,Still,House,0,False,2018-05-14 16:18:39,-1.0,32767,0,locked,0,Monday,awake,1526311119,978,180,600,25235
3,Unknown,House,0,False,2018-05-14 16:19:09,-1.0,32767,0,locked,0,Monday,awake,1526311149,979,180,600,25235
4,Still,House,0,False,2018-05-14 16:20:09,-1.0,24050,0,locked,0,Monday,awake,1526311209,980,180,600,25235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23747,Still,House,0,False,2018-06-13 12:14:37,59999.0,0,5,locked,8,Wednesday,awake,1528888477,734,0,0,0
23748,Still,House,0,False,2018-06-13 12:18:08,420000.0,0,5,locked,11,Wednesday,awake,1528888688,738,0,0,0
23749,Still,House,0,False,2018-06-13 12:19:08,359999.0,0,5,locked,11,Wednesday,awake,1528888748,739,0,0,0
23750,Still,House,0,False,2018-06-13 12:19:38,359999.0,0,5,locked,12,Wednesday,awake,1528888778,739,0,0,0
23751,Tilting,House,0,False,2018-06-13 12:20:08,299998.0,0,0,locked,0,Wednesday,awake,1528888808,740,0,0,0